on:
  workflow_call:
    inputs:
      foobar:
        description: 'foobar'
        required: true
        type: string
jobs:
  foobar:
    runs-on: ubuntu-latest
    steps:
      - name: foobar
        run: echo ${{ inputs.foobar }}

      - uses: ./.github/actions/moshi.yml
